config/routes.rb
Rails.application.routes.draw do
  resources :jogos
  resources :classificacoes
  resources :generos
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/jogo.rb
class Jogo < ApplicationRecord
    belongs_to : classificacao
    has_many :blibiotecas_de_usuario , class_name: "blibioteca"

    validates :titolo, :desenvolvedora, :lancamento, :descricao, presence: true

    scope :por_titolo, lambda{ |titolo = nil|
        if titolo
         
            where(titolo:titolo) if titolo 
        end 
    }
end

app/controllers/jogos_controller.rb
class JogosController < ApplicationController
  before_action :set_jogo, only: [:show, :edit, :update, :destroy]

  # GET /jogos
  # GET /jogos.json
  def index
    @jogos = Jogo.por_titolo (params[:titolo])
    end

  end

  # GET /jogos/1
  # GET /jogos/1.json
  def show
  end

  # GET /jogos/new
  def new
    @jogo = Jogo.new
  end

  # GET /jogos/1/edit
  def edit
  end

  # POST /jogos
  # POST /jogos.json
  def create
    @jogo = Jogo.new(jogo_params)

    respond_to do |format|
      if @jogo.save
        format.html { redirect_to actions: :index, notice: 'Jogo was successfully created.' }
        format.json { render :show, status: :created, location: @jogo }
      else
        format.html { render :new }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jogos/1
  # PATCH/PUT /jogos/1.json
  def update
    respond_to do |format|
      if @jogo.update(jogo_params)
        format.html { redirect_to @jogo, notice: 'Jogo was successfully updated.' }
        format.json { render :show, status: :ok, location: @jogo }
      else
        format.html { render :edit }
        format.json { render json: @jogo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jogos/1
  # DELETE /jogos/1.json
  def destroy
    @jogo.destroy
    respond_to do |format|
      format.html { redirect_to jogos_url, notice: 'Jogo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jogo
      @jogo = Jogo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jogo_params
      params.require(:jogo).permit(:titolo, :descrcao, :desenvolvedora, :lancamento, :classificacao_id)
    end

app/helpers/jogos_helper.rb
module JogosHelper
end

app/views/jogos/_form.html.erb
<%= form_with(model: jogo, local: true) do |form| %>
  <% if jogo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jogo.errors.count, "error") %> prohibited this jogo from being saved:</h2>

      <ul>
      <% jogo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titolo %>
    <%= form.text_field :titolo %>
  </div>

  <div class="field">
    <%= form.label :descrcao %>
    <%= form.text_area :descrcao %>
  </div>

  <div class="field">
    <%= form.label :desenvolvedora %>
    <%= form.text_field :desenvolvedora %>
  </div>

  <div class="field">
    <%= form.label :lancamennto %>
    <%= form.date_select :lancamennto %>
  </div>

  <div class="field">
    <%= form.label :classificacao_id %>
    <%= form.select :classificacao_id,
                      Classificacao.all.collect {|cl| [cl.nome, cl.id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jogos/edit.html.erb
<h1>Editing Jogo</h1>

<%= render 'form', jogo: @jogo %>

<%= link_to 'Show', @jogo %> |
<%= link_to 'Back', jogos_path %>

app/views/jogos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jogos</h1>

<table>
  <thead>
    <tr>
      <th>Titolo</th>
      <th>Descrcao</th>
      <th>Desenvolvedora</th>
      <th>Lancamennto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jogos.each do |jogo| %>
      <tr>
        <td><%= jogo.titolo %></td>
        <td><%= jogo.descrcao %></td>
        <td><%= jogo.desenvolvedora %></td>
        <td><%= jogo.lancamennto %></td>
        <td><%= link_to 'Show', jogo %></td>
        <td><%= link_to 'Edit', edit_jogo_path(jogo) %></td>
        <td><%= link_to 'Destroy', jogo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jogo', new_jogo_path %>

app/views/jogos/new.html.erb
<h1>New Jogo</h1>

<%= render 'form', jogo: @jogo %>

<%= link_to 'Back', jogos_path %>

app/views/jogos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titolo:</strong>
  <%= @jogo.titolo %>
</p>

<p>
  <strong>Descrcao:</strong>
  <%= @jogo.descrcao %>
</p>

<p>
  <strong>Desenvolvedora:</strong>
  <%= @jogo.desenvolvedora %>
</p>

<p>
  <strong>Lancamennto:</strong>
  <%= @jogo.lancamennto %>
</p>

<%= link_to 'Edit', edit_jogo_path(@jogo) %> |
<%= link_to 'Back', jogos_path %>